# Generated by Django 4.2.1 on 2023-05-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre: ")),
                (
                    "apellido",
                    models.CharField(max_length=30, verbose_name="Apellido: "),
                ),
                ("dni", models.IntegerField(verbose_name="DNI: ")),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre: ")),
                ("precio", models.FloatField(verbose_name="Precio: ")),
                ("stock_actual", models.IntegerField(verbose_name="Stock: ")),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compra.proveedor",
                    ),
                ),
            ],
        ),
    ]
