# Generated by Django 4.2.1 on 2023-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.FloatField(verbose_name="Precio"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock_actual",
            field=models.IntegerField(verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="apellido",
            field=models.CharField(max_length=30, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="dni",
            field=models.IntegerField(verbose_name="DNI"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
    ]
